### ISSUE TITLE
[Feature]: Feature to check who is currently using Dogu Studio

### ISSUE THREAD

**Issue by chachamelon** [dogu-team/dogu#316]
### Problem

It's currently not possible to know who is using it, and multiple users can connect simultaneously. Everyone can interact in this state.

* Alternatively, is there a feature that I might be using incorrectly?

### Solution brainstorm

1. Add a reservation feature.
2. Show who is currently using it.

If there's a better way, feel free to fix it that way.

**Comment by Ikalli** [comment]
Hi, @chachamelon!

We are planning a feature for Device Streaming(Dogu Studio) that will not prevent multiple people from accessing it, but will allow you to know who has connected.

The functionality to lock access(or reservation) so that others cannot connect is expected to be implemented at a later stage.

If you want to prevent others from accessing the device, it would be advisable to restrict access based on the assigned project to the device.

**Comment by Ikalli** [comment]
For reservation feature, I'll create another issue for it!

**Comment by Ikalli** [comment]
This issue is scheduled to be addressed in milestone v1.11.0 😀

**Comment by chachamelon** [comment]
thx all the time :)

**Comment by Ikalli** [comment]
Hi, @chachamelon!

This issue has been resolved as a new feature in v1.11.2 release!
Please check release note: https://github.com/dogu-team/dogu/releases/tag/v1.11.2

Thanks for suggesting good issue!👍
